apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
           - name: POSTGRES_DB
             valueFrom:
               secretKeyRef:
                 name: env-secret
                 key: DATABASE_NAME
           - name: POSTGRES_USER
             valueFrom:
               secretKeyRef:
                 name: env-secret
                 key: DATABASE_USERNAME
           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: env-secret
                 key: DATABASE_PASSWORD
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
