apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appNames.name2 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appNames.name2 }}
  template:
    metadata:
      labels:
        app: {{ .Values.appNames.name2 }}
    spec:
      imagePullSecrets:
        - name: github-secret
      containers:
        - name: {{ .Values.appNames.name2 }}
          image: {{ .Values.image.repository2 }}
          ports:
            - containerPort: {{ .Values.containerPort }}
