---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: development
spec:
  encryptedData:
    .dockerconfigjson: AgBO+yvbs/jEk0rqGvTkRtzAivLV+gjfqZj54IWPLeacYTgVoJKuO4n1Tb9v/J6ePhOiuZicQRBlQEuX+DWayzYER5HPvCH1is6RpKiCIAhyww/dOExtQg2C/VsiBaQXP/C++Qc2wGnBcHoAFnwE0NM9FR6BcEms81nfVHVLPXMVMkZsMopUGeyuCTsectX3qVvY1mr2/L1412pmwbegu0vd9rAcDLd+B0PNzmO17bTslbWPcN99JNg8TIeF1no9/mcQb4hI8R5JneUfMAYc/UReiUn/4zeUZ1IN3fkFLs36zQVuV3Cz1EtaU7jIw0pDar25wZ/B+2jDAJwpz/yAVnnStH96071hiNNloMUp8B7h+MXsWv6m++wyXOuxtcRbqwBGNK2pwxpuVntN07UytiKV3fS0kI69bb91jkfiatBiAkmuzK0q8S4Fk6tQnEbljISeVKZlMwBp58mYUSP3qsZ3uXIxLgtiHtdKebrerUTnQcrQBZSkdvWrqgSwSGMw7pWJ6OnbBxk+L1o19GEeW02YfCFghnPG9X/4u3ZF9pkgr+moEiYSCHMquMXb39Majm1xDpfGN1wSDlJWzkjMcTqSzWeiGr+fa6DkdQYU3Wnbn5KfgRqWDEYkCHvZYSBtKXrJAaBqtJiM1rjfZGIRDOLmVlY3iEO/AscVIZwkUe6oj7/P4rJw7C9uiKRyRkSxScTqK5liiI6ACEVSqA/Z8qGnCaC/iPKSHKG3BeEpMa7J2NpfOe4mbSMrTEHg/HxbagRDeYYdVPBkO6LgdOkJT8xg9VVIePfDbf33vjEJjq+kq0eg2GVLYuD5kBolCwMBJNutsTtyEv9nJYtHEdY3/XYDzupQx1Ep1SsJKBHUFdCMx5STHgO7PlWOxyUJMw==
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: development
    type: kubernetes.io/dockerconfigjson
