apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.services.service1.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appNames.name1 }}
  ports:
    - protocol: {{ .Values.services.service1.protocol }}
      port: {{ $.Values.services.service1.ports.number }}
      targetPort: {{ $.Values.services.service1.ports.number }}
