apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
  namespace: yt_downloader
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
