apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yt-downloader
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: yt_downloader
    repoURL: https://github.com/infinity-step/final_project/helm
    targetRevision: 1.0.0
  syncPolicy:
    automated: {}
