apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yt-downloader-dev
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: yt_downloader
    repoURL: https://infinity-step.github.io/final_project/helm
targetRevision: /
  syncPolicy:
    automated: {}
