apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "django.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "django.fullname" . }}
    spec:
      imagePullSecrets:
        - name: github-secret
      containers:
        - name: {{ include "django.fullname" . }}
          image: "{{ .Values.image.repository }}"
          envFrom:
            - secretRef:
                name: env-secret
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
