apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "django.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.storageClassName }}
