apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "django.fullname" . }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.ports.number }}
      targetPort: {{ .Values.service.ports.number }}
