name: tests forr project
on:
  push:
    branches:
    - dev
jobs:
  start_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: start tests
        run: |
          sudo apt-get install python3-pip
          pip3 install yt_dlp
          python3 ./yt_downloader/back/yt_downloader/yt_app/tests.py
