name: tests for project
on:
  push:
    branches:
    - dev
jobs:
  start_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: start tests
        run: |
          yt_v=$(grep "^yt_dlp==" ./yt_downloader/back/yt_downloader/requirements.txt)
          pip3 install $yt_v
          python3 ./yt_downloader/back/yt_downloader/yt_app/tests.py
