name: tests for project
on:
  push:
    branches:
    - dev
jobs:
  start_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: start tests
        run: |
          sudo apt-get install python3-pip
          yt_v=$(grep "^yt_dlp==" ./yt_downloader/back/yt_downloader/requirements.txt | cut -d'=' -f2)
          echo $yt_v
          pip3 install yt_dlp==$yt_v
          python3 ./yt_downloader/back/yt_downloader/yt_app/tests.py
