name: Dockerfile Linting

on:
  push:
    branches:
    - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: dockerfiles/django_dockerfile
      
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: dockerfiles/react_dockerfile
          
      - name: Send Slack notification
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "blocks": [
              {
                "type": "section",
                 "text": {
                  "type": "mrkdwn",
                  "text": ":mag: *Результаты Hadolint: ${{ steps.hadolint.outcome }}*"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Коммит:* ${{ github.sha }}"
                  }
                ]
              },
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
