name: Dockerfile Linting

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [dockerfiles/django_dockerfile, dockerfiles/react_dockerfile]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hadolint
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          format: json

      - name: Prepare and Send Slack Notification
        if: always()
        run: |
          if [ ${{ steps.hadolint.outcome }} == 'success' ]; then
            STATUS="✅ Проверка прошла успешно"
          else
            STATUS="❌ Обнаружены ошибки в ${{ matrix.dockerfile }}"
          fi
          
          JSON_PAYLOAD="{\"text\": \"🔍 Проверка ${{ matrix.dockerfile }} завершена. Статус: $STATUS\"}"

          curl -X POST -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
