name: tests
on:
  push:
    branches:
    - master
jobs:
  start_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: start tests
        run: python3 tests.py
